name: CI

on:
  workflow_dispatch: {}

  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy: &platform-strategy
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        php: [ 8.2, 8.3, 8.4, 8.5 ]
        dependency-version: [ prefer-lowest, prefer-stable ]
    name: Check style (php${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }})
    steps:
      - uses: actions/checkout@v5

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: Run linter
        run: composer run-script tests:lint

  refactor:
    runs-on: ${{ matrix.os }}
    strategy: *platform-strategy
    name: Check refactor (php${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: Run static analyser
        run: composer run-script tests:refactor

  types:
    runs-on: ${{ matrix.os }}
    strategy: *platform-strategy
    name: Check types (php${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: Run static analyser
        run: composer run-script tests:types

  tests:
    runs-on: ${{ matrix.os }}
    strategy: *platform-strategy
    name: Run tests (php${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }})
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

      - name: Run unit tests
        run: composer run-script tests:unit

      - name: Run integration tests
        run: composer run-script tests:integration
